[config]
schemaVersion = "0.0.1"


[package]
namespace = "erumi321"
name = "UILibrary"
versionNumber = "0.2.1"
description = "Library for other mods to use that handles more complex UI elements"
websiteUrl = "https://github.com/erumi321/Hades2UILibrary"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.48"
SGG_Modding-ENVY = "1.1.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "4.0.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "libraries", ]
